name: dream2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+23
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_database: ^10.0.0
  intl_phone_field: ^3.2.0
  #otp_text_field:
  font_awesome_flutter: ^10.4.0
  pin_code_text_field: ^1.8.0
  flutter_screenutil: ^5.6.1
  get: ^4.6.4
  dio: ^4.0.0
  cached_network_image: ^3.2.2
  skeleton_text: ^3.0.0
  shared_preferences: ^2.1.2
  google_fonts: ^4.0.3
 # intl: ^0.17.0
  logger: ^1.4.0
  fluttertoast: ^8.2.1
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.8
  carousel_slider: ^4.2.0
  #progress_dialog:
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^3.0.0
  pin_code_fields: ^7.4.0
  cloud_firestore: ^4.3.2
  provider: ^6.0.3
  modal_progress_hud_nsn: ^0.2.0
  bdaya_fcm_handler: ^5.0.0
  firebase_messaging: ^14.6.2
  cloud_functions: ^4.0.8
  assets_audio_player: ^3.0.6
  flutter_audio_recorder2: ^0.0.2
  firebase_storage: ^11.0.11
  audioplayers: ^0.20.1
  flutter_localization: ^0.1.7



  flutter_slidable: ^0.6.0
  dotted_border:

  flutter_launcher_icons: ^0.9.2




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.jpeg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/flags/
    - assets/audios/
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
